### ISSUE TITLE
Add real enemies

### ISSUE THREAD

**Issue by TNielsen92pro** [GreatGameDevs/GreatGame#15]
Some sort of real enemy should be added so that we get the main interactions working and so we are able to add more enemies quickly later.

**Comment by jianguda** [comment]
I plan to use these assets for enemies:
https://assetstore.unity.com/packages/3d/characters/meshtint-free-boximon-fiery-mega-toon-series-153958
https://assetstore.unity.com/packages/3d/characters/meshtint-free-boximon-cyclopes-mega-toon-series-154436

**Comment by jianguda** [comment]
#22 added enemies
