### ISSUE TITLE
Add a visual effect when snowball is destroyed

### ISSUE THREAD

**Issue by urbanturban** [GreatGameDevs/GreatGame#19]
When the snowball collides with something (like wall of a house) and the snowball is destroyed, add a visual effect showing it.

**Comment by jianguda** [comment]
I guess `rigidbody.AddExplosionForce(...)` should make sense.

**Comment by jianguda** [comment]
#21 added one feature that snowball recovers its gravity after collision, and disappear when timer is over. (Because we need make snowball be composed by several parts to an explosion effect, or we could consider particle system)
