### ISSUE TITLE
Add different levels of christmassyness

### ISSUE THREAD

**Issue by TNielsen92pro** [GreatGameDevs/GreatGame#31]
We should get a feeling of how the different levels of christmassyness looks

**Comment by urbanturban** [comment]
@thelmasv did these relating to this issue:
- Added 3 steps of xmas decorations in scene

I'll work on some type of progression controller to trigger the levels.

**Comment by TNielsen92pro** [comment]
Progression state handler added

**Comment by urbanturban** [comment]
#62 added music progression

**Comment by urbanturban** [comment]
645d5401bd2ecadd6aea117e5dc16a99b81b2cc6 added snowfall progression

**Comment by urbanturban** [comment]
084aadf19480bdcd58be296d88b6068cca0cb596 added scene brightness progression

**Comment by urbanturban** [comment]
#58 added more christmas deco among other things
