### ISSUE TITLE
Add animated gift receiving NPCs

### ISSUE THREAD

**Issue by urbanturban** [GreatGameDevs/GreatGame#33]
The NPCs that receive gifts should be animals of different kinds and perhaps be able to celebrate/cheer make noises when interacting with the players.

- 3D models
- Sounds
- Animations

**Comment by urbanturban** [comment]
Needed to know what the riddles are and what animals are needed. Added some suggestions in GDD #28

**Comment by TNielsen92pro** [comment]
This issue can probably be considered done
